services:

  django:
    build:
      context: ./mfh_django
      dockerfile: Dockerfile.prod
    container_name: mfh_django
    env_file: ./mfh_django/.env
    volumes:
      - ./mfh_django:/app
    expose:
      - "8000"

  react:
    build:
      context: ./mfh_react
      dockerfile: Dockerfile.prod
    container_name: mfh_react
    environment:
      - DJANGO_API_URL=http://django:8000
    expose:
      - "80"
    depends_on:
      - django

  proxy:
    image: nginx:alpine
    container_name: mfh_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - react
      - django
