server {
    listen 80;

    # Redirige la racine vers /mfh/
    location = / {
        return 301 /mfh/;
    }

    # API Django — appelée par React depuis le navigateur (/api/...)
    location /api/ {
        proxy_pass       http://django:8000/api/;
        proxy_set_header Host            $host;
        proxy_set_header X-Real-IP       $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Application MFH (React SPA)
    location /mfh/ {
        proxy_pass       http://react:80/;
        proxy_set_header Host            $host;
        proxy_set_header X-Real-IP       $remote_addr;
    }

    # Future : /jorat/
    # location /jorat/ {
    #     proxy_pass http://jorat:80/;
    # }
}
