# Generated by Django 6.0.3 on 2026-03-13 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenom_client', models.CharField(max_length=150)),
                ('cin_client', models.CharField(blank=True, max_length=20, null=True)),
                ('tel_client', models.CharField(blank=True, max_length=20, null=True)),
                ('email_client', models.EmailField(blank=True, max_length=254, null=True)),
                ('obs_client', models.TextField(blank=True, null=True)),
                ('statut_client', models.CharField(blank=True, choices=[('AQUEREUR', 'AQUEREUR'), ('SOCIETE', 'SOCIETE')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenom', models.CharField(max_length=150)),
                ('email_comm', models.EmailField(blank=True, max_length=254, null=True)),
                ('tel_comm', models.CharField(blank=True, max_length=20, null=True)),
                ('obs_comm', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenom_not', models.CharField(max_length=150)),
                ('email_notaire', models.EmailField(blank=True, max_length=254, null=True)),
                ('tel_notaire', models.CharField(blank=True, max_length=20, null=True)),
                ('obs_notaire', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateField(blank=True, null=True)),
                ('date_vente', models.DateField(blank=True, null=True)),
                ('date_desistement', models.DateField(blank=True, null=True)),
                ('prix_vente', models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True)),
                ('situation_dossier', models.CharField(choices=[('RESERVATION', 'Réservation'), ('VENTE', 'Vente'), ('DESISTEMENT', 'Désistement')], default='RESERVATION', max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mfh.client')),
                ('commercial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mfh.commercial')),
            ],
        ),
        migrations.CreateModel(
            name='Caisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_caisse', models.DateField()),
                ('reference_caisse', models.CharField(blank=True, max_length=100)),
                ('montant_recu', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_livre', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('type_ops', models.CharField(choices=[('RESERVATION', 'Réservation'), ('COMPLEMENT', 'Avance'), ('VENTE', 'Vente')], max_length=20)),
                ('obs_caisse', models.CharField(blank=True, max_length=200)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation', to='mfh.dossier')),
            ],
            options={
                'verbose_name': 'Opération',
                'verbose_name_plural': 'Opérations de caisse',
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilot', models.IntegerField(default=0)),
                ('lot', models.IntegerField(default=0)),
                ('tranche', models.CharField(blank=True, max_length=6)),
                ('n_titre', models.CharField(blank=True, max_length=20, null=True)),
                ('categorie', models.CharField(max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=200, null=True)),
                ('surface', models.IntegerField(default=0, null=True)),
                ('prix_reference', models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True)),
                ('situation', models.CharField(default='LIBRE', max_length=10)),
                ('obs_lot', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['ilot', 'lot'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('n_titre__isnull', False), models.Q(('n_titre', ''), _negated=True)), fields=('n_titre',), name='uniq_lot_n_titre_if_filled')],
            },
        ),
        migrations.AddField(
            model_name='dossier',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to='mfh.lot'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='notaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mfh.notaire'),
        ),
        migrations.AddConstraint(
            model_name='dossier',
            constraint=models.UniqueConstraint(condition=models.Q(('actif', True)), fields=('lot',), name='unique_dossier_actif_par_lot'),
        ),
    ]
