# Generated by Django 6.0.3 on 2026-03-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfh', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caisse',
            options={'ordering': ['date_caisse'], 'verbose_name': 'Opération', 'verbose_name_plural': 'Opérations de caisse'},
        ),
        migrations.AlterField(
            model_name='caisse',
            name='type_ops',
            field=models.CharField(choices=[('RESERVATION', 'Réservation'), ('COMPLEMENT', 'Avance / Complément'), ('VENTE', 'Vente'), ('REMBOURSEMENT', 'Remboursement')], max_length=20),
        ),
    ]
