# Generated by Django 6.0.3 on 2026-03-13 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mfh', '0002_alter_caisse_options_alter_caisse_type_ops'),
    ]

    operations = [
        migrations.RunSQL(
            sql="UPDATE mfh_dossier SET actif = 0 WHERE situation_dossier = 'DESISTEMENT' AND actif = 1;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
