# Generated by Django 6.0.3 on 2026-03-16 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfh', '0004_sync_lot_situation'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='commercial_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots_en_option', to='mfh.commercial'),
        ),
        migrations.AddField(
            model_name='lot',
            name='date_option',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lot',
            name='situation',
            field=models.CharField(choices=[('LIBRE', 'Libre'), ('OPTION', 'Option'), ('RESERVE', 'Réservé'), ('VENDU', 'Vendu')], default='LIBRE', max_length=10),
        ),
        migrations.CreateModel(
            name='HistoriqueLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('OPTION_ACTIVE', 'Option activée'), ('OPTION_ANNULEE', 'Option annulée')], max_length=20)),
                ('date_action', models.DateField(auto_now_add=True)),
                ('obs', models.CharField(blank=True, max_length=200)),
                ('commercial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique_lots', to='mfh.commercial')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='mfh.lot')),
            ],
            options={
                'verbose_name': 'Historique lot',
                'verbose_name_plural': 'Historique des lots',
                'ordering': ['-date_action', '-id'],
            },
        ),
    ]
