# Generated by Django 6.0.3 on 2026-03-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfh', '0007_dossier_prix_vente_encrypted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('DIRECTEUR', 'Directeur'), ('VIEWER', 'Lecteur'), ('COMMERCIAL', 'Commercial')], default='VIEWER', max_length=20),
        ),
    ]
